# Essa versão é a última tag do Github
adguard_version: "v0.107.72"
adguard_donwload_file: "AdGuardHome_linux_amd64.tar.gz"

# Donwload das releases do Github
adguard_url: "https://github.com/AdguardTeam/AdGuardHome/releases/download/{{ adguard_version }}/{{ adguard_donwload_file }}"

# Local padrão de instalação do Adguard
adguard_installation_dir: "/opt"
adguard_archive: "{{ adguard_installation_dir }}/{{ adguard_donwload_file }}"
