# This version is the latest tag from GitHub
adguard_version: "v0.107.72"
adguard_download_file: "AdGuardHome_linux_amd64.tar.gz"

# Download from GitHub releases
adguard_url: "https://github.com/AdguardTeam/AdGuardHome/releases/download/{{ adguard_version }}/{{ adguard_download_file }}"

# Default AdGuard installation location
adguard_installation_dir: "/opt"
adguard_archive: "{{ adguard_installation_dir }}/{{ adguard_download_file }}"
