---
- name: "Proxmox init-configure"
  hosts: proxmox_nodes
  gather_facts: no
  become: yes

  roles:
    - proxmox-create-user
    - proxmox-customize-rocky-linux-cloud-image
    - proxmox-create-cloud-init-vm-template
    - terraform-create-vms