---
- name: "Proxmox Destroy"
  hosts: proxmox_nodes
  gather_facts: no
  become: yes

  roles:
    - role: proxmox-remove-nfs
      tags: "destroy-infra"

    - role: terraform-destroy-vms
      tags: "destroy-infra"

    - role: proxmox-reset
      tags: "reset-proxmox"

    - role: clean-local-files
      tags: "reset-proxmox"