---
- name: "Proxmox init-configure"
  hosts: proxmox_nodes
  gather_facts: no
  become: yes

  # vars_files:
  #   - group_vars/config.yaml

  tasks:

    ##################################################################
    # Remove VM Template
    ##################################################################
    - name: "Remove VM Template"
      shell: "{{ item }}"
      loop:
        - "qm stop {{ cloud_init_template.vm_id }}"
        - "qm destroy {{ cloud_init_template.vm_id }}"


    ##################################################################
    # Remove User
    ##################################################################
    - name: "Remove User"
      shell: "{{ item }}"
      loop:
        - "pveum user delete {{ iac_user }}"
        - "pveum role del {{ iac_role }}"


    ##################################################################
    # Remove Temporary folder
    ##################################################################
    - name: "Delete temporary folder and image file"
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ config_cloud_image_directory }}"
        # - "{{ rocky_linux_cloud_image_file }}"