---
- name: "Proxmox init-configure"
  hosts: proxmox
  gather_facts: no
  become: yes


  tasks:

      ##################################################################
      # Remove NFS
      ##################################################################
    - name: "Check if {{ nfs_storage_name }} storage exists"
      shell: "pvesm list NFS"
      register: nfs_exists
      ignore_errors: yes

    - name: "Check if mount point {{ nfs_mount_point }} exists"
      stat:
        path: "{{ nfs_mount_point }}"
      register: nfs_dir_exists

    - name: "Remove NFS Storage"
      shell: "{{ item }}"
      loop:
        - "pvesm remove {{ nfs_storage_name }}"
      when: nfs_exists.rc == 0

    - name: "Remove NFS Mount Point"
      shell: "{{ item }}"
      loop:
        - "umount {{ nfs_mount_point }}"
        - "rm -rf {{ nfs_mount_point }}"
      when: nfs_dir_exists.stat.exists

