---

##############################################
# Desinstalando o k3s
##############################################
- name: "Uninstall o k3s"
  hosts: k8s_cluster
  become: true
  gather_facts: no

  roles:
    - kubernetes-uninstall