---
##############################################
# Executando em todos os hosts
##############################################
- name: "Creating the user and configuring ssh"
  hosts: all
  become: yes
  gather_facts: yes

  vars_files:
    - group_vars/dns_and_k3s_config.yaml

  roles:
    - create-user # talvez não precise
    - create-ssh-config # atualiza o .ssh/config do meu client


##############################################
# Executando apenas no grupo 'nfs_server_hosts'
##############################################
- name: "Configuring NFS Server"
  hosts: nfs_server_hosts
  become: yes
  gather_facts: no

  roles:
    - nfs-server

##############################################
# Configurando NFS nos clients
##############################################
- name: "Configuring NFS on clients"
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - nfs-client

#############################################
# Executando apenas no grupo 'nfs_server_hosts'
#############################################
- name: "Configuring the DNS Server"
  hosts: dns_server_host
  remote_user: pihole
  become: yes
  gather_facts: no

  vars_files:
    - group_vars/dns_and_k3s_config.yaml

  roles:
    - docker-install
    - restart-machine
    - dns-server


##############################################
# Configurando DNS nos clients
##############################################
- name: "Configuring DNS on clients"
  hosts: all
  become: yes
  gather_facts: yes

  vars_files:
    - group_vars/dns_and_k3s_config.yaml

  roles:
    - dns-client

##############################################
# Abrindo porta 6443 no Firewall no cluster k8s
##############################################
- name: "Applying firewall settings to k8s cluster nodes"
  hosts: k8s_cluster
  become: yes
  gather_facts: yes

  roles:
    - kubernetes-firewall