---

- name: "Wait for SSH to be available"
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    port: 22
    delay: 30
    timeout: 600
    state: started
  delegate_to: localhost
  become: false

- name: "Reset known_hosts entry"
  become: false
  command: ssh-keygen -R {{ ansible_host }}
  delegate_to: localhost
  changed_when: false

- name: "Ensure SSH key is on remote host"
  delegate_to: localhost
  become: false
  ssh_copy_key:
    host: "{{ ansible_host }}"
    user: "{{ ansible_user }}"
    password: "{{ root_password }}"
    public_key_file: "{{ ssh_public_key_file }}"
