---
- name: Setup Garage S3
  ansible.builtin.import_tasks: setup.yml

- name: Configure Garage
  ansible.builtin.import_tasks: configure.yml

- name: Configure AWS CLI local
  ansible.builtin.import_tasks: aws_cli.yml

- name: Manage Buckets
  ansible.builtin.import_tasks: buckets.yml
