---
# Disable firewall for Kubernetes cluster nodes
# Ubuntu uses UFW by default

- name: "Disable UFW firewall service"
  become: true
  ansible.builtin.systemd:
    name: ufw
    state: stopped
    enabled: false
