- name: "Install libguestfs-tools package"
  ansible.builtin.apt:
    name: libguestfs-tools
    state: present
    update_cache: yes

- name: "Create a temporary directory in root's home"
  ansible.builtin.file:
    path: "{{ config_cloud_image_directory }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: "Download Ubuntu 24.04 Cloud image file"
  ansible.builtin.get_url:
    url: "{{ ubuntu_cloud_image_url }}"
    dest: "{{ ubuntu_cloud_image_file }}"
    force: true

- name: "Customize Cloud Init Image"
  ansible.builtin.shell: |
    virt-customize -a {{ ubuntu_cloud_image_file }} \
      --timezone "America/Recife" \
      --install qemu-guest-agent,nano,vim,wget,figlet \
      --run-command "systemctl enable qemu-guest-agent" \
      --run-command "sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config" \
      --run-command "sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config" \
      --run-command "sed -i 's/^#\?KbdInteractiveAuthentication.*/KbdInteractiveAuthentication yes/' /etc/ssh/sshd_config" \
      --run-command "systemctl enable ssh" \
      --run-command "systemctl start ssh" \
      --run-command "sed -i 's/^disable_root:.*$/disable_root: false/' /etc/cloud/cloud.cfg" \
      --run-command "sed -i 's/^lock_passwd:.*$/lock_passwd: false/' /etc/cloud/cloud.cfg" \
      --run-command "sed -i 's/^ssh_pwauth:.*$/ssh_pwauth: true/' /etc/cloud/cloud.cfg" \
      --root-password password:{{ ubuntu_cloud_image_root_password }} \
      --run-command "passwd -u root" \
      --run-command "truncate -s 0 /etc/machine-id"
  changed_when: true
