---

- name: "Create a temporary directory in root's home"
  ansible.builtin.file:
    path: "{{ config_cloud_image_directory }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: "Define ssh_public_key_file variable"
  ansible.builtin.set_fact:
    vm_ssh_public_key: "{{ config_cloud_image_directory }}/id_rsa_homelab.pub"

- name: "Copy ssh public key to remote server"
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: "{{ ssh_public_key_file }}", dest: "{{ vm_ssh_public_key }}" }

- name: "Check if VM Template already exists"
  ansible.builtin.shell: qm list | grep -q "{{ cloud_init_template.vm_id }}"
  register: vm_exists
  failed_when: false
  ignore_errors: true

- name: "Create Cloud Init VM Template (Ubuntu 24.04)"
  community.proxmox.proxmox_kvm:
    api_host: "{{ ansible_host }}"
    api_user: "{{ ansible_user }}@pam"
    api_password: "{{ root_password }}"
    node: "{{ proxmox_target_node }}"
    vmid: "{{ cloud_init_template.vm_id }}"
    name: "{{ cloud_init_template.vm_template_name }}"
    state: present
    # Hardware
    machine: q35
    memory: 1024
    cores: 1
    cpu: host
    scsihw: virtio-scsi-pci
    # Disks
    scsi:
      scsi0: "{{ cloud_init_template.vm_storage }}:0,import-from={{ ubuntu_cloud_image_file }},format=qcow2,discard=on,ssd=1"
    ide:
      ide2: "{{ cloud_init_template.vm_storage }}:cloudinit"
    # Network
    net:
      net0: "virtio,bridge=vmbr0"
    # Cloud-Init
    agent: "enabled=1"
    ciuser: "{{ cloud_init_template.vm_username }}"
    cipassword: "{{ cloud_init_template.vm_user_password }}"
    sshkeys: "{{ lookup('file', ssh_public_key_file) }}"
    citype: configdrive2
    ipconfig:
      ipconfig0: "ip=dhcp"
    boot: "order=scsi0"

- name: "Convert VM to Template"
  ansible.builtin.command: "qm template {{ cloud_init_template.vm_id }}"
  changed_when: true
  when: vm_exists.rc != 0

- name: "Wait for Proxmox API to stabilize"
  ansible.builtin.pause:
    seconds: 15
  when: vm_exists.rc != 0
