
all:

  #####################################################################
  # Global variables
  #####################################################################
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ssh_public_key_file: ""
    ssh_private_key_file: ""

    ########################### K3s ###########################
    # k3s token, used by installation on master and joins nodes
    k3s_token: ""

    # flag to enable (or not) to master execute pods
    # Set to "true" if you want to master execute pods. Set to "false" otherwise
    master_execute_pod: true
    node_taint: "{{ '' if master_execute_pod else '--node-taint CriticalAddonsOnly=true:NoExecute' }}"

    # generic script to install k3s
    k3s_install_script: "curl -sfL https://get.k3s.io | K3S_TOKEN={{ k3s_token }} sh -s -"

    #############################################
    # K3s Server installation
    #############################################
    k3s_server_install_parameters: "{{ node_taint }} --write-kubeconfig-mode=644 --disable servicelb --disable traefik"
    k3s_server_install_command: "{{ k3s_install_script }} server {{ k3s_server_install_parameters }}"

    #############################################
    # K3s Agent installation
    #############################################
    k3s_node_install_parameters: "--server https://{{ hostvars[groups['k8s_masters_nodes'][0]]['ansible_host'] }}:6443"
    k3s_node_install_command: "{{ k3s_install_script }} agent {{ k3s_node_install_parameters }}"

  hosts:
    #####################################################################
    # Proxmox Nodes
    #####################################################################
    proxmox:
      ansible_host: ""
      ansible_user: root
      root_password: ""
      proxmox_target_node: ""

      # NFS storage
      nfs_storage_name: "NFS"
      nfs_mount_point: "/mnt/pve/{{ nfs_storage_name }}"

      # Proxmox user role config
      iac_user: ""
      iac_user_password: ""
      iac_role: "terraform-role"
      iac_role_permissions: "VM.Allocate VM.Clone VM.Config.CDROM VM.Config.CPU VM.Config.Cloudinit VM.Config.Disk VM.Config.HWType VM.Config.Memory VM.Config.Network VM.Config.Options VM.Monitor VM.Audit VM.PowerMgmt Datastore.AllocateSpace Datastore.Audit SDN.Allocate SDN.Audit SDN.Use"

      # VM Template with cloud init image, config
      cloud_init_ansible.builtin.template:
        vm_id: ""
        vm_template_name: ""
        vm_storage: "local-lvm"
        vm_username: ""
        vm_user_password: ""

      # auxiliar and temporary file
      user_token_output_file: "/tmp/terraform_user_token.txt"
      # local copy of the file for future reference
      user_token_output_file_localhost: "{{ playbook_dir }}/../config-files/my-configs/{{ user_token_output_file | basename }}"

      # Cloud init image config
      config_cloud_image_directory: "/root/config-cloud-image"
      rocky_linux_cloud_image_url: "https://download.rockylinux.org/pub/rocky/8/images/x86_64/Rocky-8-GenericCloud-Base.latest.x86_64.qcow2"
      rocky_linux_cloud_image_file: "/var/lib/vz/images/rocky8.qcow2"
      rocky_linux_cloud_image_root_password: "RockyLinux"

    #####################################################################
    #  VMs
    #####################################################################
    ############# SINGLE VM: NFS
    nfs:
      ansible_host:
      ansible_user:
      root_password:
      vm_user:
      vm_user_passwd:
      nfs_folder: "/home/nfs/data"

      # values relative to VM in proxmox
      proxmox_vm_id:
      proxmox_cpu:
      proxmox_memory:
      proxmox_vm_name:
      proxmox_vm_network_ip_suffix:
      proxmox_vm_disk_size:
      proxmox_vm_tags: "nfs"

    ############# SINGLE VM: DNS
    dns:
      ansible_host:
      ansible_user:
      root_password:
      vm_user:
      vm_user_passwd:

      # values relative to VM in proxmox
      proxmox_vm_id:
      proxmox_cpu:
      proxmox_memory:
      proxmox_vm_name:
      proxmox_vm_network_ip_suffix:
      proxmox_vm_disk_size:
      proxmox_vm_tags:

      # External DNS (It can be Google DNS for example: 8.8.8.8)
      # This IP is only used in /etc/resolv.conf of DNS Server (Pihole in this case)
      external_dns_server: "8.8.8.8"

      # pihole admin password, in the browser
      pihole_password:

    ############# K8S CLUSTER: K8s Masters
    k8s-master:
      ansible_host:
      ansible_user:
      root_password:
      vm_user:
      vm_user_passwd:

      # Values relative to VM in proxmox
      # Just need to add these variables, in the first node.
      proxmox_vm_id:
      proxmox_cpu:
      proxmox_vm_name: '["NAME_1", "NAME_2", "NAME_3"]'
      proxmox_vm_network_ip_suffix:
      proxmox_memory:
      proxmox_vm_disk_size:
      proxmox_vm_tags: "TAG_1,TAG_2"

    ############# K8S CLUSTER: K8s Workers
    k8s-worker-1:
      ansible_host:
      ansible_user:
      root_password:
      vm_user:
      vm_user_passwd:

      # Values relative to VM in proxmox
      # Just need to add these variables, in the first node.
      proxmox_vm_id:
      proxmox_cpu:
      proxmox_vm_name: '["NAME_1", "NAME_2", "NAME_3"]'
      proxmox_vm_network_ip_suffix:
      proxmox_memory:
      proxmox_vm_disk_size:
      proxmox_vm_tags: "TAG_1,TAG_2"

    k8s-worker-2:
      ansible_host:
      ansible_user:
      root_password:
      vm_user:
      vm_user_passwd:


#####################################################################
#  Hosts Groups
#####################################################################
  children:

    # Proxmox Nodes
    proxmox_nodes:
      hosts:
        proxmox:

    # DNS Servers
    dns_server_hosts:
      hosts:
        dns:

    # NFS Servers
    nfs_server_hosts:
      hosts:
        nfs:

    # K8s Masters nodes
    k8s_masters_nodes:
      hosts:
        k8s-master:

    # K8s Workers nodes
    k8s_worker_nodes:
      hosts:
        k8s-worker-1:
        k8s-worker-2:

    # k8s Cluster nodes
    k8s_cluster:
      children:
        k8s_masters_nodes:
        k8s_worker_nodes:

    # All Vms
    vms_all:
      children:
        k8s_cluster:
        dns_server_hosts:
        nfs_server_hosts:

    # All Vms EXCEPT k8s cluster vms
    single_vms:
      children:
        dns_server_hosts:
        nfs_server_hosts:
