all:

  #####################################################################
  # Global variables
  #####################################################################
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ssh_public_key_file: "{{ lookup('ansible.builtin.env', 'HOME') }}/.ssh/id_rsa_homelab.pub"
    ssh_private_key_file: "{{ lookup('ansible.builtin.env', 'HOME') }}/.ssh/id_rsa_homelab"

    network_gateway: ""

    ########################### K3s ###########################
    # k3s token, used by installation on master and joins nodes
    k3s_token: ""

    # flag to enable (or not) to master execute pods
    # Set to "true" if you want to master execute pods. Set to "false" otherwise
    master_execute_pod: true
    node_taint: "{{ '' if master_execute_pod else '--node-taint CriticalAddonsOnly=true:NoExecute' }}"

    # generic script to install k3s
    k3s_install_script: "curl -sfL https://get.k3s.io | K3S_TOKEN={{ k3s_token }} sh -s -"

    # K3s Server installation
    k3s_server_install_parameters: "{{ node_taint }} --write-kubeconfig-mode=644 --disable servicelb --disable traefik"
    k3s_server_install_command: "{{ k3s_install_script }} server {{ k3s_server_install_parameters }}"

    # K3s Agent installation
    k3s_node_install_parameters: "--server https://{{ hostvars[groups['k8s_masters_nodes'][0]]['ansible_host'] }}:6443"
    k3s_node_install_command: "{{ k3s_install_script }} agent {{ k3s_node_install_parameters }}"

  hosts:
    #####################################################################
    # Proxmox Nodes
    #####################################################################
    proxmox:
      ansible_host: ""
      ansible_user: "root"
      root_password: ""
      proxmox_target_node: ""

      # VM Template with cloud init image, config
      cloud_init_template:
        vm_id: ""
        vm_template_name: ""
        vm_storage: "local-lvm"
        vm_username: ""
        vm_user_password: ""

      # Cloud init image config
      config_cloud_image_directory: "/root/config-cloud-image"
      ubuntu_cloud_image_url: "https://download.rockylinux.org/pub/rocky/8/images/x86_64/Rocky-8-GenericCloud-Base.latest.x86_64.qcow2"
      ubuntu_cloud_image_file: "/var/lib/vz/images/ubuntu24.qcow2"
      ubuntu_cloud_image_root_password: "Ubuntu"

    #####################################################################
    # VMs and Containers LXC
    #####################################################################

    ############# Container: DNS
    dns:
      ansible_host: ""
      ansible_user: ""
      root_password: ""
      vm_user: ""
      vm_user_passwd: ""

      # values relative to VM in proxmox
      proxmox_vm_id: 
      proxmox_cpu: 1
      proxmox_memory: 1024
      proxmox_vm_name: ""
      proxmox_vm_disk_size: "20G"
      proxmox_vm_tags: "dns"

      ansible_python_interpreter: /usr/bin/python3.11
      note_icon_url: "https://raw.githubusercontent.com/frankjuniorr/homelab-iac/main/images/icons/adguard-icon.png"

    ############# Container: Storage (Garage S3)
    s3:
      ansible_host: ""
      ansible_user: ""
      root_password: ""
      vm_user: ""
      vm_user_passwd: ""

      proxmox_vm_id: 
      proxmox_cpu: 1
      proxmox_memory: 1024
      proxmox_vm_name: "jupiter"
      proxmox_vm_disk_size: "40G"
      proxmox_vm_tags: "storage,s3,backup"

      ansible_python_interpreter: /usr/bin/python3.11
      note_icon_url: "https://raw.githubusercontent.com/frankjuniorr/homelab-iac/main/images/icons/garage-s3.png"

    ############# VMS: K8s Cluster: K8s Masters
    k8s-master:
      ansible_host: ""
      ansible_user: ""
      root_password: ""
      vm_user: ""
      vm_user_passwd: ""

      # Values relative to VM in proxmox
      # Just need to add these variables, in the first node.
      proxmox_vm_id: 
      proxmox_cpu: 2
      proxmox_vm_name: ""
      proxmox_memory: 6144
      proxmox_vm_disk_size: "20G"
      proxmox_vm_tags: "k8s,masters"

      ansible_python_interpreter: /usr/bin/python3.11
      note_icon_url: "https://raw.githubusercontent.com/frankjuniorr/homelab-iac/main/images/icons/kubernetes-icon.png"

    ############# K8S CLUSTER: K8s Workers
    k8s-worker-1:
      ansible_host: ""
      ansible_user: ""
      root_password: ""
      vm_user: ""
      vm_user_passwd: ""

      # Values relative to VM in proxmox
      # Just need to add these variables, in the first node.
      proxmox_vm_id: 
      proxmox_cpu: 2
      proxmox_vm_name: ""
      proxmox_memory: 8192
      proxmox_vm_disk_size: "20G"
      proxmox_vm_tags: "k8s,workers"

      ansible_python_interpreter: /usr/bin/python3.11
      note_icon_url: "https://raw.githubusercontent.com/frankjuniorr/homelab-iac/main/images/icons/kubernetes-icon.png"

    k8s-worker-2:
      ansible_host: ""
      ansible_user: ""
      root_password: ""
      vm_user: ""
      vm_user_passwd: ""

      proxmox_vm_name: ""
      proxmox_vm_id: 
      proxmox_cpu: 2
      proxmox_memory: 8192
      proxmox_vm_disk_size: "20G"
      proxmox_vm_tags: "k8s,workers"

      ansible_python_interpreter: /usr/bin/python3.11
      note_icon_url: "https://raw.githubusercontent.com/frankjuniorr/homelab-iac/main/images/icons/kubernetes-icon.png"


#####################################################################
#  Hosts Groups
#####################################################################
  children:

    # Proxmox Nodes
    proxmox_nodes:
      hosts:
        proxmox:

    # DNS Servers
    dns_server_hosts:
      hosts:
        dns:

    # Garage Storage
    garage_hosts:
      hosts:
        s3:

    # LXC Containers
    containers_lxc:
      hosts:
        dns:
        s3:

    # K8s Masters nodes
    k8s_masters_nodes:
      hosts:
        k8s-master:

    # K8s Workers nodes
    k8s_worker_nodes:
      hosts:
        k8s-worker-1:
        k8s-worker-2:

    # k8s Cluster nodes
    k8s_cluster:
      children:
        k8s_masters_nodes:
        k8s_worker_nodes:

    # All Vms
    vms_all:
      children:
        k8s_cluster:

    # All Vms EXCEPT k8s cluster vms
    single_vms:
      children:
        dns_server_hosts:
        garage_hosts:
