---

# Operation System used by VMs with Cloud Init
# avaliable values:
# - "ubuntu"
# - "rocky"
operation_system: 'ubuntu'

# terraform user in Proxmox
iac_user: "proxmox_user@pve"
iac_user_password: "mypassword"

# VM Template with cloud init image, config
vm_id: "999"
vm_storage: "local-lvm"
vm_username: "vm_user"
vm_user_password: "vm_password"
dns_server: "192.168.0.1"