---
ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

# generic script to install k3s
k3s_install_script: "curl -sfL https://get.k3s.io | K3S_TOKEN={{ k3s_token }} sh -s -"

#############################################
# K3s Server installation
#############################################
k3s_server_install_parameters: "{{ node_taint }} --write-kubeconfig-mode=644 --disable servicelb --disable traefik"
k3s_server_install_command: "{{ k3s_install_script }} server {{ k3s_server_install_parameters }}"

#############################################
# K3s Agent installation
#############################################
k3s_node_install_parameters: "--server https://{{ hostvars[groups['k8s_masters'][0]]['ansible_host'] }}:6443"
k3s_node_install_command: "{{ k3s_install_script }} agent {{ k3s_node_install_parameters }}"

