---
garage_version: "2.2.0"
garage_arch: "x86_64-unknown-linux-musl"
garage_binary_url: "https://garagehq.deuxfleurs.fr/_releases/v{{ garage_version }}/{{ garage_arch }}/garage"

garage_config_dir: "/etc"
garage_data_dir: "/var/lib/garage"
garage_meta_dir: "/var/lib/garage/meta"
garage_data_storage_dir: "/var/lib/garage/data"

garage_rpc_bind_addr: "[::]:3901"
garage_s3_api_bind_addr: "[::]:3900"
garage_s3_region: "homelab"

garage_admin_api_bind_addr: "[::]:3903"
garage_metrics_bind_addr: "[::]:3902"

##########################################################
# Lista de Buckets
##########################################################
garage_buckets:
  - name: adguard-bucket
    permissions:
      - read
      - write

