---

# Donwload Rocky Linux container image
#############################################################################
- name: "Choose Rocky Linux container image"
  ansible.builtin.shell: "pveam available | grep \"rocky\" | awk '{print $2}'"
  register: container_image

- name: "Donwload Rocky Linux container image"
  ansible.builtin.shell: "pveam download local {{ container_image.stdout }}"
  args:
    creates: "/var/lib/vz/template/cache/{{ container_image.stdout }}"

# Create LXC Containers
#############################################################################
- name: Criar container LXC no Proxmox
  ansible.builtin.shell: |
    pct create {{ hostvars[item].proxmox_vm_id }} /var/lib/vz/template/cache/{{ container_image.stdout }} \
        --hostname {{ hostvars[item].proxmox_vm_name }} \
        --storage {{ cloud_init_template.vm_storage }} \
        --rootfs {{ cloud_init_template.vm_storage }}:8 \
        --cores {{ hostvars[item].proxmox_cpu }} \
        --memory {{ hostvars[item].proxmox_memory }} \
        --net0 name=eth0,bridge=vmbr0,ip={{ hostvars[item].ansible_host }}/24,gw={{ hostvars[item].network_gateway }} \
        --password {{ hostvars[item].root_password }} \
        --ssh-public-keys /root/.ssh/id_rsa.pub \
        --start 1
  args:
    creates: "/etc/pve/lxc/{{ hostvars[item].proxmox_vm_id }}.conf"
  loop: "{{ groups['dns_server_hosts'] }}"
  loop_control:
    label: "{{ hostvars[item].proxmox_vm_name }}"
  register: container_creation

- name: "Pause to wait VMs to be ready"
  ansible.builtin.pause:
    seconds: 20
  when: container_creation.changed


- name: Renderizar script de configuração do container
  ansible.builtin.template:
    src: configure_container.sh.j2
    dest: "/tmp/configure_container_{{ hostvars[item].proxmox_vm_id }}.sh"
    mode: '0755'
  loop: "{{ groups['dns_server_hosts'] }}"
  loop_control:
    label: "{{ hostvars[item].proxmox_vm_name }}"
  vars:
    vm_user: "{{ hostvars[item].vm_user }}"
    vm_user_passwd: "{{ hostvars[item].vm_user_passwd }}"
    vm_ssh_public_key: "{{ hostvars[item].ssh_public_key_file }}"
  when: container_creation.changed

- name: Copiar script para dentro do container
  ansible.builtin.shell: |
    pct push {{ hostvars[item].proxmox_vm_id }} /tmp/configure_container_{{ hostvars[item].proxmox_vm_id }}.sh /root/configure_container.sh --perms 0755
  become: true
  loop: "{{ groups['containers_lxc'] }}"
  loop_control:
    label: "{{ hostvars[item].proxmox_vm_name }}"
  when: container_creation.changed

- name: Executar script dentro do container
  ansible.builtin.shell: |
    pct exec {{ hostvars[item].proxmox_vm_id }} -- bash /root/configure_container.sh
    pct exec {{ hostvars[item].proxmox_vm_id }} -- bash -c \
        "echo '{{ lookup('file', ssh_public_key_file) }}' >> /home/{{ hostvars[item].vm_user }}/.ssh/authorized_keys"
  become: true
  loop: "{{ groups['containers_lxc'] }}"
  loop_control:
    label: "{{ hostvars[item].proxmox_vm_name }}"
  when: container_creation.changed
