---
- name: "Update apt cache"
  become: true
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: "Upgrade all packages to the latest version (dist-upgrade)"
  become: true
  ansible.builtin.apt:
    upgrade: dist
    autoremove: yes
    purge: yes

- name: "Cleanup apt cache"
  become: true
  ansible.builtin.apt:
    autoclean: yes
    clean: yes

- name: "Check if reboot is required"
  become: true
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: "Restart machine if reboot is required"
  ansible.builtin.reboot:
    msg: "Rebooting to apply kernel updates"
    reboot_timeout: 600
  when: reboot_required.stat.exists
