---
- name: "Check for package updates"
  ansible.builtin.dnf:
    update_cache: yes

- name: "Add repository"
  ansible.builtin.shell: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: "Install Docker packages"
  ansible.builtin.shell: dnf -y install docker-ce docker-ce-cli containerd.io docker-compose-plugin

- name: "Start Docker service"
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: "Add user to docker group"
  ansible.builtin.user:
    name: "{{ vm_user }}"
    groups: docker
    append: yes