---

# terraform user in Proxmox
iac_user: "terraform@pve"
iac_user_password: "Terraform!@#$"

# VM Template with cloud init image, config
vm_id: "900"
vm_template_name: "rocky8-cloud-init-template"
vm_storage: "local-lvm"
vm_username: "devops"
vm_user_password: "devops"