---
##################################################################
# Remove VM Template
##################################################################
- name: "Check for locked VMs"
  ansible.builtin.shell: find /etc/pve -type f -name '*.conf' -exec grep -H 'lock:' {} \; | wc -l
  register: vm_lock_check
  changed_when: false

- name: "Unlock VM"
  ansible.builtin.shell: qm unlock {{ cloud_init_template.vm_id }}
  when: vm_lock_check.stdout | int > 0

- name: "Remove VM Template"
  ansible.builtin.shell: "{{ item }}"
  loop:
    - "qm stop {{ cloud_init_template.vm_id }}"
    - "qm destroy {{ cloud_init_template.vm_id }}"
  ignore_errors: yes
  register: vm_template_status
  failed_when: "'unable to find configuration file for VM' in vm_template_status.stderr and 'qm destroy' in item"

##################################################################
# Remove User
##################################################################
- name: "Remove User"
  ansible.builtin.shell: "{{ item }}"
  loop:
    - "pveum user delete {{ iac_user }}"
    - "pveum role del {{ iac_role }}"
  register: delete_role_output
  ignore_errors: yes
  failed_when: "'delete role failed' in delete_role_output.stderr and ('pveum role del' in item and 'role' not in item)"


##################################################################
# Remove Temporary folder
##################################################################
- name: "Delete temporary folder and image file"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ config_cloud_image_directory }}"
    # - "{{ rocky_linux_cloud_image_file }}"
    # - "{{ rocky_linux_cloud_image_file_sha }}"