---
- name: Setup RClone
  ansible.builtin.import_tasks: setup.yml

- name: Create Sync Scripts
  ansible.builtin.import_tasks: scripts.yml

- name: Recovery Data
  ansible.builtin.import_tasks: recovery.yml

- name: Schedule Backups
  ansible.builtin.import_tasks: cron.yml
