---
- name: "Install RClone"
  ansible.builtin.shell: "curl -sS https://rclone.org/install.sh | bash"
  become: true
  args:
    creates: /usr/bin/rclone

- name: "Ensure RClone configuration directory exists"
  ansible.builtin.file:
    path: "{{ rclone_config_dir }}"
    state: directory
    mode: '0700'
  when: inventory_hostname != 'localhost'

- name: "Configure RClone"
  ansible.builtin.template:
    src: "rclone_{{ inventory_hostname }}.conf.j2"
    dest: "{{ rclone_config_file }}"
    mode: '0600'
  when: 
    - inventory_hostname != 'localhost'

- name: "Ensure RClone configuration directory exists for root"
  become: true
  ansible.builtin.file:
    path: "/root/.config/rclone"
    state: directory
    mode: '0700'
  when: inventory_hostname != 'localhost'

- name: "Copy RClone config to root"
  become: true
  ansible.builtin.copy:
    src: "/home/{{ hostvars[inventory_hostname]['ansible_user'] }}/.config/rclone/rclone.conf"
    dest: "/root/.config/rclone/rclone.conf"
    remote_src: true
    mode: '0600'
  when: inventory_hostname != 'localhost'

############################################################################
# Scripts de Sincronização
############################################################################

- name: "Create backup scripts directory"
  ansible.builtin.file:
    path: "{{ rclone_backup_scripts_dir }}"
    state: directory
    mode: '0755'
  when: inventory_hostname != 'localhost'

- name: "Create AdGuard sync script (DNS Container)"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ rclone_backup_scripts_dir }}/{{ item.dest }}"
    mode: '0755'
  loop:
    - { src: "backup-adguard-to-s3.sh.j2", dest: "backup-adguard-to-s3.sh" } 
    - { src: "recovery-adguard-from-s3.sh.j2", dest: "recovery-adguard-from-s3.sh" } 
  when: inventory_hostname == 'dns'

- name: "Create Garage sync script (S3 Container)"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ rclone_backup_scripts_dir }}/{{ item.dest }}"
    mode: '0755'
  loop:
    - { src: "backup-s3-to-gdrive.sh.j2", dest: "backup-s3-to-gdrive.sh" } 
    - { src: "recovery-gdrive-from-s3.sh.j2", dest: "recovery-gdrive-from-s3.sh" } 
  when: inventory_hostname == 's3'

- name: "Check if Adguard already have configured"
  become: true
  ansible.builtin.stat:
    path: /opt/AdGuardHome/AdGuardHome.yaml
  register: adguard_conf
  when: inventory_hostname == 'dns'

- name: "Check if adguard-bucket are empty"
  become: true
  ansible.builtin.command: >
    rclone lsjson {{ garage_s3_remote_name }}:{{ adguard_bucket_name }}
  register: bucket_content
  changed_when: false
  when: inventory_hostname == 's3'

- name: "Recovery Garage Buckets from Google Drive"
  become: true
  ansible.builtin.shell: "bash {{ rclone_backup_scripts_dir }}/recovery-gdrive-from-s3.sh"
  when:
    - inventory_hostname == 's3'
    - (bucket_content.stdout | from_json) | length == 0

- name: "Recovery Adguard data from S3"
  become: true
  ansible.builtin.shell: "bash {{ rclone_backup_scripts_dir }}/recovery-adguard-from-s3.sh"
  when:
    - inventory_hostname == 'dns'
    - not adguard_conf.stat.exists
