---
- name: "Create PostgreSQL user '{{ postgres_user }}'"
  community.postgresql.postgresql_user:
    name: "{{ postgres_user }}"
    password: "{{ postgres_app_password }}"
    state: present
  become: true
  become_user: postgres

- name: "Check encoding of existing database '{{ postgres_db }}'"
  community.postgresql.postgresql_query:
    login_db: postgres
    query: "SELECT pg_encoding_to_char(encoding) AS encoding FROM pg_database WHERE datname = '{{ postgres_db }}'"
  register: db_encoding_check
  become: true
  become_user: postgres
  failed_when: false

- name: "Drop database '{{ postgres_db }}' if encoding is not UTF8"
  community.postgresql.postgresql_db:
    name: "{{ postgres_db }}"
    state: absent
  become: true
  become_user: postgres
  when:
    - db_encoding_check.query_result | length > 0
    - db_encoding_check.query_result[0]['encoding'] != 'UTF8'

- name: "Create PostgreSQL database '{{ postgres_db }}'"
  community.postgresql.postgresql_db:
    name: "{{ postgres_db }}"
    owner: "{{ postgres_user }}"
    encoding: "UTF8"
    lc_collate: "C.UTF-8"
    lc_ctype: "C.UTF-8"
    template: "template0"
    state: present
  become: true
  become_user: postgres
