---
########################################################
# Remove VM Template
#################################################################
- name: "Remove VM Template"
  shell: "{{ item }}"
  loop:
    - "qm stop {{ cloud_init_template.vm_id }}"
    - "qm destroy {{ cloud_init_template.vm_id }}"
  ignore_errors: yes
  register: vm_template_status
  failed_when: "'unable to find configuration file for VM' in vm_template_status.stderr and 'qm destroy' in item"

##################################################################
# Remove User
##################################################################
- name: "Remove User"
  shell: "{{ item }}"
  loop:
    - "pveum user delete {{ iac_user }}"
    - "pveum role del {{ iac_role }}"


##################################################################
# Remove Temporary folder
##################################################################
- name: "Delete temporary folder and image file"
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ config_cloud_image_directory }}"
    # - "{{ rocky_linux_cloud_image_file }}"
    # - "{{ rocky_linux_cloud_image_file_sha }}"