
all:

  #####################################################################
  # Global variables
  #####################################################################
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    ssh_public_key_file: "/home/frank/.ssh/id_rsa_homelab.pub"
    ssh_private_key_file: "/home/frank/.ssh/id_rsa_homelab"

    network_gateway: "192.168.0.1"

    ########################### K3s ###########################
    # k3s token, used by installation on master and joins nodes
    k3s_token: '@Jg_6_Ex6.PMicZRzym8fHTUgTM*@C'

    # flag to enable (or not) to master execute pods
    # Set to "true" if you want to master execute pods. Set to "false" otherwise
    master_execute_pod: true
    node_taint: "{{ '' if master_execute_pod else '--node-taint CriticalAddonsOnly=true:NoExecute' }}"

    # generic script to install k3s
    k3s_install_script: "curl -sfL https://get.k3s.io | K3S_TOKEN={{ k3s_token }} sh -s -"

    #############################################
    # K3s Server installation
    #############################################
    k3s_server_install_parameters: "{{ node_taint }} --write-kubeconfig-mode=644 --disable servicelb --disable traefik"
    k3s_server_install_command: "{{ k3s_install_script }} server {{ k3s_server_install_parameters }}"

    #############################################
    # K3s Agent installation
    #############################################
    k3s_node_install_parameters: "--server https://{{ hostvars[groups['k8s_masters_nodes'][0]]['ansible_host'] }}:6443"
    k3s_node_install_command: "{{ k3s_install_script }} agent {{ k3s_node_install_parameters }}"

  hosts:
    #####################################################################
    # Proxmox Nodes
    #####################################################################
    proxmox:
      ansible_host: 192.168.0.115
      ansible_user: root
      root_password: "Proxmox!@#$"
      proxmox_target_node: "hyperspace01"

      # NFS storage
      nfs_storage_name: "NFS"
      nfs_mount_point: "/mnt/pve/{{ nfs_storage_name }}"

      # VM Template with cloud init image, config
      cloud_init_template:
        vm_id: "900"
        vm_template_name: "rocky8-cloud-init-template"
        vm_storage: "local-lvm"
        vm_username: "devops"
        vm_user_password: "devops"

      # Cloud init image config
      config_cloud_image_directory: "/root/config-cloud-image"
      rocky_linux_cloud_image_url: "https://download.rockylinux.org/pub/rocky/8/images/x86_64/Rocky-8-GenericCloud-Base.latest.x86_64.qcow2"
      rocky_linux_cloud_image_file: "/var/lib/vz/images/rocky8.qcow2"
      rocky_linux_cloud_image_root_password: "RockyLinux"

    #####################################################################
    #  VMs
    #####################################################################
    ############# SINGLE VM: NFS
    nfs:
      ansible_host: 192.168.0.50
      ansible_user: nfs
      root_password: devops
      vm_user: nfs
      vm_user_passwd: devops
      nfs_folder: "/home/nfs/data"

      # values relative to VM in proxmox
      proxmox_vm_id: 300
      proxmox_cpu: 2
      proxmox_memory: 2048
      proxmox_vm_name: "jupiter"
      proxmox_vm_disk_size: "50G"
      proxmox_vm_tags: "nfs"

      ansible_python_interpreter: /usr/bin/python3.11

    ############# SINGLE VM: DNS
    dns:
      ansible_host: 192.168.0.51
      ansible_user: pihole
      root_password: devops
      vm_user: pihole
      vm_user_passwd: devops

      # values relative to VM in proxmox
      proxmox_vm_id: 301
      proxmox_cpu: 2
      proxmox_memory: 2048
      proxmox_vm_name: "saturno"
      proxmox_vm_disk_size: "20G"
      proxmox_vm_tags: "dns"

      # External DNS (It can be Google DNS for example: 8.8.8.8)
      # This IP is only used in /etc/resolv.conf of DNS Server (Pihole in this case)
      external_dns_server: "8.8.8.8"

      # pihole admin password, in the browser
      pihole_password: admin

      ansible_python_interpreter: /usr/bin/python3.11

    ############# K8S CLUSTER: K8s Masters
    k8s-master:
      ansible_host: 192.168.0.60
      ansible_user: k8s-master
      root_password: devops
      vm_user: k8s-master
      vm_user_passwd: devops

      # Values relative to VM in proxmox
      # Just need to add these variables, in the first node.
      proxmox_vm_id: 400
      proxmox_cpu: 2
      # proxmox_vm_name: '["brahma", "shiva", "vishnu"]'
      proxmox_vm_name: "brahma"
      proxmox_memory: 5120
      proxmox_vm_disk_size: "20G"
      proxmox_vm_tags: "k8s,masters"

      ansible_python_interpreter: /usr/bin/python3.11

    ############# K8S CLUSTER: K8s Workers
    k8s-worker-1:
      ansible_host: 192.168.0.70
      ansible_user: k8s-worker-1
      root_password: devops
      vm_user: k8s-worker-1
      vm_user_passwd: devops

      # Values relative to VM in proxmox
      # Just need to add these variables, in the first node.
      proxmox_vm_id: 500
      proxmox_cpu: 2
      # proxmox_vm_name: '["ganesha", "krishna", "lakshmi"]'
      proxmox_vm_name: "ganesha"
      proxmox_memory: 6144
      proxmox_vm_disk_size: "20G"
      proxmox_vm_tags: "k8s,workers"

      ansible_python_interpreter: /usr/bin/python3.11

    k8s-worker-2:
      ansible_host: 192.168.0.71
      ansible_user: k8s-worker-2
      root_password: devops
      vm_user: k8s-worker-2
      vm_user_passwd: devops

      proxmox_vm_name: "krishna"
      proxmox_vm_id: 501
      proxmox_cpu: 2
      proxmox_memory: 6144
      proxmox_vm_disk_size: "20G"
      proxmox_vm_tags: "k8s,workers"

      ansible_python_interpreter: /usr/bin/python3.11


#####################################################################
#  Hosts Groups
#####################################################################
  children:

    # Proxmox Nodes
    proxmox_nodes:
      hosts:
        proxmox:

    # DNS Servers
    dns_server_hosts:
      hosts:
        dns:

    # NFS Servers
    nfs_server_hosts:
      hosts:
        nfs:

    # K8s Masters nodes
    k8s_masters_nodes:
      hosts:
        k8s-master:

    # K8s Workers nodes
    k8s_worker_nodes:
      hosts:
        k8s-worker-1:
        k8s-worker-2:

    # k8s Cluster nodes
    k8s_cluster:
      children:
        k8s_masters_nodes:
        k8s_worker_nodes:

    # All Vms
    vms_all:
      children:
        k8s_cluster:
        dns_server_hosts:
        nfs_server_hosts:

    # All Vms EXCEPT k8s cluster vms
    single_vms:
      children:
        dns_server_hosts:
        nfs_server_hosts:
