---
##############################################
# Proxmox Init Configure
##############################################
- name: "Proxmox init-configure"
  hosts: proxmox_nodes
  gather_facts: false
  become: true

  roles:
    
    # Create Containers
    - role: proxmox-create-containers
      tags:
        - proxmox-init


    # Create VMs
    - role: proxmox-customize-rocky-linux-cloud-image
      tags:
        - proxmox-init

    - role: proxmox-create-cloud-init-vm-template
      tags:
        - proxmox-init

    - role: proxmox-create-vms
      tags:
        - proxmox-init

    - role: proxmox-write-notes
      vars:
        proxmox_guest_group: "{{ groups['vms_all'] }}"
        proxmox_guest_type: "vm"
      tags:
        - proxmox-init

    - role: proxmox-write-notes
      vars:
        proxmox_guest_group: "{{ groups['containers_lxc'] }}"
        proxmox_guest_type: "container"
      tags:
        - proxmox-init


##############################################
# Running in all hosts
##############################################
- name: "Creating the user and configuring ssh"
  hosts: all
  become: true
  gather_facts: false

  roles:
    - role: configure-remote-ssh
      tags:
        - deploy-infra

# #############################################
# # Executing only in 'dns_server_hosts'
# #############################################
- name: "Configuring the DNS Server"
  hosts: dns_server_hosts
  remote_user: adguard
  become: true
  gather_facts: false

  roles:
    - role: dns-server
      tags:
        - deploy-infra


##############################################
# Running in all hosts
##############################################
- name: "Configure all VMs"
  hosts: vms_all
  become: true
  gather_facts: false

  roles:
    - role: configure-vm-user
      tags:
        - deploy-infra

    - role: dns-client
      tags:
        - deploy-infra


##############################################
# Opening 6443 port on cluster k8s Firewall
##############################################
- name: "Applying firewall settings to k8s cluster nodes"
  hosts: k8s_cluster
  become: true
  gather_facts: true

  roles:
    - role: kubernetes-firewall
      tags:
        - deploy-infra

##############################################
# Installing k3s
##############################################
- name: "Installing k3s servers"
  hosts: k8s_masters_nodes
  become: true
  gather_facts: false

  roles:
    - role: kubernetes-install-masters
      tags:
        - deploy-infra
        - k3s-install

- name: "Installing k3s nodes"
  hosts: k8s_worker_nodes
  become: true
  gather_facts: false

  roles:
    - role: kubernetes-install-nodes
      tags:
        - deploy-infra
        - k3s-install
