---

- name: "Check if AdGuardHome is responding on port 80"
  delegate_to: localhost
  become: false
  ansible.builtin.wait_for:
    host: "{{ hostvars[backup_dns_host]['ansible_host'] }}"
    port: 80
    timeout: 3
  register: adguard_port_check
  ignore_errors: yes

- name: "Wait for manual AdGuardHome configuration"
  delegate_to: localhost
  become: false
  ansible.builtin.pause:
    prompt: "Configure o Adguard, acesse: http://{{ hostvars[backup_dns_host]['ansible_host'] }}:3000 . Pressione ENTER quando terminar para seguir com o backup."
  when: adguard_port_check is failed

- name: "Ensure local backup directory is clean"
  delegate_to: localhost
  become: false
  ansible.builtin.file:
    path: "{{ backup_local_dir }}"
    state: "{{ item }}"
    mode: '0755'
  loop:
    - absent
    - directory
  when: adguard_port_check is true

- name: "Backup AdGuardHome data"
  delegate_to: "{{ backup_dns_host }}"
  become: yes
  block:
    - name: "Create backup archive on DNS server"
      ansible.builtin.command:
        cmd: "tar -czf /tmp/{{ backup_prefix }}_temp.tar.gz -C {{ adguard_dir }} AdGuardHome.yaml data"
      register: tar_output
      changed_when: tar_output.rc == 0

    - name: "Fetch backup to local machine"
      ansible.builtin.fetch:
        src: "/tmp/{{ backup_prefix }}_temp.tar.gz"
        dest: "{{ backup_local_dir }}/{{ backup_prefix }}_{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}.tar.gz"
        flat: yes

    - name: "Remove temporary backup file on DNS server"
      ansible.builtin.file:
        path: "/tmp/{{ backup_prefix }}_temp.tar.gz"
        state: absent
  when:
    - backup_dns_host in groups['all']
    - adguard_port_check is true

